# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1.0
      with:
        bazel-version: '3.2.0'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: bazel test //...
