name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: l.gcr.io/google/bazel:3.5.0
    steps:
      - name: install bazelisk
        run: |
          curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x /usr/local/bin/bazel
          which bazel
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: /github/home/.bazel_cache
          key: ${{ github.ref }}
          restore-keys: |
            ${{ github.ref }}
            refs/heads/master
      - name: Buildbuddy
        run: |
          echo "${{ secrets.BUILDBUDDY_CERT_PEM }}">buildbuddy-cert.pem
          sha256sum buildbuddy-cert.pem
          echo "${{ secrets.BUILDBUDDY_KEY_PEM }}">buildbuddy-key.pem
          sha256sum buildbuddy-key.pem
      - name: Run tests
        run: bazel test --repository_cache=/github/home/.bazel_cache //... --config=remote
